// <auto-generated />
using System;
using ApiGenerico.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiGenerico.Infrastructure.Migrations
{
    [DbContext(typeof(ContextSql))]
    partial class ContextSqlModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiGenerico.Domain.Entities.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("State", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 9, 14, 38, 48, 692, DateTimeKind.Utc).AddTicks(4619),
                            Name = "Pendiente",
                            UpdatedAt = new DateTime(2025, 12, 9, 14, 38, 48, 692, DateTimeKind.Utc).AddTicks(4622)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 9, 14, 38, 48, 692, DateTimeKind.Utc).AddTicks(4625),
                            Name = "En Progreso",
                            UpdatedAt = new DateTime(2025, 12, 9, 14, 38, 48, 692, DateTimeKind.Utc).AddTicks(4625)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 9, 14, 38, 48, 692, DateTimeKind.Utc).AddTicks(4627),
                            Name = "Completado",
                            UpdatedAt = new DateTime(2025, 12, 9, 14, 38, 48, 692, DateTimeKind.Utc).AddTicks(4627)
                        });
                });

            modelBuilder.Entity("ApiGenerico.Domain.Entities.TaskEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DueDate");

                    b.HasIndex("StateId");

                    b.ToTable("Task", (string)null);
                });

            modelBuilder.Entity("ApiGenerico.Domain.Entities.TaskHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("NewStateId")
                        .HasColumnType("int");

                    b.Property<int?>("PreviousStateId")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NewStateId");

                    b.HasIndex("PreviousStateId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskHistory", (string)null);
                });

            modelBuilder.Entity("ApiGenerico.Domain.Entities.TaskEntity", b =>
                {
                    b.HasOne("ApiGenerico.Domain.Entities.State", "State")
                        .WithMany("Tasks")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("ApiGenerico.Domain.Entities.TaskHistory", b =>
                {
                    b.HasOne("ApiGenerico.Domain.Entities.State", "NewState")
                        .WithMany()
                        .HasForeignKey("NewStateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiGenerico.Domain.Entities.State", "PreviousState")
                        .WithMany()
                        .HasForeignKey("PreviousStateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ApiGenerico.Domain.Entities.TaskEntity", "Task")
                        .WithMany("TaskHistories")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewState");

                    b.Navigation("PreviousState");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("ApiGenerico.Domain.Entities.State", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("ApiGenerico.Domain.Entities.TaskEntity", b =>
                {
                    b.Navigation("TaskHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
